### ISSUE TITLE
bug: Timed Out 

### ISSUE THREAD

**Issue by TheMaltese-Hacker** [PassTheMayo/minecraft-server-util#54]
This Happenes when I link a server that is on, btw the server is on cause i tested it on mcsrvstat.us

code:
Error: Timed out while waiting for server response
    at UDPSocket.readPacket (/home/runner/Daddy-Bot-1/node_modules/minecraft-server-util/dist/structure/UDPSocket.js:46:75)
    at Object.<anonymous> (/home/runner/Daddy-Bot-1/node_modules/minecraft-server-util/dist/statusBedrock.js:65:45)
    at Generator.next (<anonymous>)
    at fulfilled (/home/runner/Daddy-Bot-1/node_modules/minecraft-server-util/dist/statusBedrock.js:5:58)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

**Comment by PassTheMayo** [comment]
Just looking at the stack trace, you're using `statusBedrock()`? Also what IP address are you testing with so I can reproduce? I'm gonna need more information than this.

**Comment by BochilGaming** [comment]
> Just looking at the stack trace, you're using `statusBedrock()` or `query<Full>`? Also what IP address are you testing with so I can reproduce? I'm gonna need more information than this.

same issue, I used ```statusBedrock()``` and it appears like that

**Comment by squeaky2137** [comment]
Same issue here on statusBedrock()

**Comment by PassTheMayo** [comment]
This seems to have been fixed in some of the newer versions. If anybody experiences this issue again, I will open this back up.
