### ISSUE TITLE
bug: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by Fatonndev** [PassTheMayo/minecraft-server-util#61]
Ping error:
```log
TypeError: Cannot read property 'length' of undefined
    at parseText (/home/api-v2/node_modules/minecraft-motd-util/dist/parse.js:49:33)
    at parseChat (/home/api-v2/node_modules/minecraft-motd-util/dist/parse.js:80:18)
    at exports.parse (/home/api-v2/node_modules/minecraft-motd-util/dist/parse.js:123:18)
    at Object.<anonymous> (/home/api-v2/node_modules/minecraft-server-util/dist/status.js:54:62)
    at Generator.next (<anonymous>)
    at fulfilled (/home/api-v2/node_modules/tslib/tslib.js:112:62)
    at processTicksAndRejections (node:internal/process/task_queues:94:5)
```

**Code:**
```javascript
const data = await MinecraftServer.status('obvilion.ru', 25565);
```

**Comment by PassTheMayo** [comment]
I was able to reproduce this issue on my end and determined the problem. I just published an update for the `minecraft-motd-util` library, so please use `npm install minecraft-motd-util@1.1.8` in your terminal and verify this issue was fixed.

**Comment by Fatonndev** [comment]
Ok, thanks
