### ISSUE TITLE
bug: Expected 'port' to be a 'number', got 'object'

### ISSUE THREAD

**Issue by xMefy** [PassTheMayo/minecraft-server-util#75]
**Describe the bug:**
When I run the command, I get an error in the console

**Code:**
```javascript
const util = require('minecraft-server-util');

module.exports = {
    name: 'minecraft',
    description: 'get information about a minecraft server',
    execute(client, message, args, Discord){
        if(!args[0]) return message.channel.send('Please enter a minecraft server ip');
        if(!args[1]) return message.channel.send('Please enter a minecraft server port');

        util.status(args[0], {port: parseInt(args[1])}).then((response) =>{
            console.log(response);
            const embed = new Discord.MessageEmbed()
            .setColor('#BFCDEB')
            .setTitle('Mc server status')
            .addFields(
                {name: 'Server IP', value: response.host},
                {name: 'Online Players', value: response.onlinePlayers},
                {name: 'Max Players', value: response.maxPlayers},
                {name: 'Version', value: response.version}
            )
            .setFooter('Mc server util by CodeLyon');

            message.channel.send(embed);
        })
        .catch ((error) =>{
            message.channel.send('there was an error finding this server');
            throw error;
        })
    }
}
```

**Expected behavior:**
When I run the command I get this error in the console:
node:assert:399
    throw err;
    ^

AssertionError [ERR_ASSERTION]: Expected 'port' to be a 'number', got 'object'
    at Object.status (C:\Users\Adam\Documents\Euforic\node_modules\minecraft-server-util\dist\status.js:24:26)
    at Object.execute (C:\Users\Adam\Documents\Euforic\commands\minecraft.js:10:14)
    at module.exports (C:\Users\Adam\Documents\Euforic\events\guild\message.js:10:25)
    at Client.emit (node:events:520:28)
    at MessageCreateAction.handle (C:\Users\Adam\Documents\Euforic\node_modules\discord.js\src\client\actions\MessageCreate.js:34:18)
    at Object.module.exports [as MESSAGE_CREATE] (C:\Users\Adam\Documents\Euforic\node_modules\discord.js\src\client\websocket\handlers\MESSAGE_CREATE.js:4:32)
    at WebSocketManager.handlePacket (C:\Users\Adam\Documents\Euforic\node_modules\discord.js\src\client\websocket\WebSocketManager.js:351:31)
    at WebSocketShard.onPacket (C:\Users\Adam\Documents\Euforic\node_modules\discord.js\src\client\websocket\WebSocketShard.js:444:22)
    at WebSocketShard.onMessage (C:\Users\Adam\Documents\Euforic\node_modules\discord.js\src\client\websocket\WebSocketShard.js:301:10)
    at WebSocket.onMessage (C:\Users\Adam\Documents\Euforic\node_modules\ws\lib\event-target.js:199:18) {
  generatedMessage: false,
  code: 'ERR_ASSERTION',
  actual: false,
  expected: true,
  operator: '=='
}

**Additional context**
Add any other context about the problem here

**Comment by PassTheMayo** [comment]
This is because you’re using an outdated example which was meant for v4 of this library. You can view the examples for the current v5 on the docs linked in the README.
